from PageClasses.BasePage import BasePage
from PageClasses.BrokenImagePage import BrokenImagePage
from PageClasses.DropdownPage import DropdownPage
from PageClasses.DynamicControlsPage import DynamicControlsPage
from PageClasses.FormAuthenticationPage import FormAuthPage
from PageClasses.AddElementPage import AddElementPage
from PageClasses.LandingPage import LandingPage