name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check ChromeDriver version
      run: |
        chromedriver --version

    - name: Check Chrome version
      run: |
        google-chrome --version

    - name: Run tests
      env:
        DISPLAY: :99.0
      run: |
        pytest -v --maxfail=10 --disable-warnings --junitxml=junit/test-results.xml || true

    - name: Generate test report
      run: |
        echo "Generating test report..."
        echo "::set-output name=report_path::junit/test-results.xml"
        echo "Test report generated."
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: junit/test-results.xml
      
